/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ittepic.literaciones;

import com.ittepic.literaciones.Custom.optimizar;
import com.formdev.flatlaf.FlatLightLaf;
import org.antlr.v4.runtime.*;
import org.antlr.v4.runtime.tree.*;
import com.ittepic.literaciones.Custom.*;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Arrays;
import java.util.List;
import java.util.Map;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.Timer;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import org.antlr.v4.gui.TreeViewer;

/**
 *
 * @author jaime
 */
public class IDE extends javax.swing.JFrame {

    NumeroLinea numerolinea;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(IDE.class.getName());
    private Coloreador coloreador;
    private Timer coloreadoTimer; // Objeto Timer
    private final int DELAY_MS = 250; // 250 milisegundos de espera

    /**
     * Creates new form Menu
     */
    public IDE() {
        initComponents();
        inicializar();

        this.coloreador = new Coloreador(jtpCode);

        // 1. Configuración del Timer (se ejecuta el coloreado cuando termina el DELAY)
        coloreadoTimer = new Timer(DELAY_MS, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                coloreador.colorear(); // El trabajo pesado se hace aquí
            }
        });
        coloreadoTimer.setRepeats(false); // Solo se ejecuta una vez por ciclo

        // 2. DocumentListener llama al Timer.restart(), no al coloreador.colorear()
        jtpCode.getDocument().addDocumentListener(new DocumentListener() {
            public void insertUpdate(DocumentEvent e) {
                coloreadoTimer.restart(); // ✅ Inicia/Reinicia la cuenta regresiva
            }

            public void removeUpdate(DocumentEvent e) {
                coloreadoTimer.restart(); // ✅ Inicia/Reinicia la cuenta regresiva
            }

            public void changedUpdate(DocumentEvent e) {
                coloreadoTimer.restart();
            }
        });
        //  ImageIcon icono = new ImageIcon(getClass().getResource("/multimedia/Logo ITT.png"));
//lbllogo = new JLabel(icono); // Pones el icono directamente
    }
    private CustomLexer lexer;
    private CommonTokenStream tokens;
    private CustomParser parser;
    private ParseTree arbol;
    // --- FIN DE LÍNEAS A AÑADIR ---

    private void inicializar() {
        //Para que se muestren las lineas dentro del textPane
        numerolinea = new NumeroLinea(jtpCode);

        ScrollCode.setRowHeaderView(numerolinea);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        tabbedPane = new javax.swing.JTabbedPane();
        OutputPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtaOutput = new javax.swing.JTextArea();
        TokenPanel = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblTokens = new javax.swing.JTable();
        SimbolPanel = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblSimbol = new javax.swing.JTable();
        SemanticoPanel = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtpSeman = new javax.swing.JTextPane();
        intermedioPanel = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jtpIntermedio = new javax.swing.JTextPane();
        optimizadoPanel = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jtpOptimizado = new javax.swing.JTextPane();
        ScrollCode = new javax.swing.JScrollPane();
        jtpCode = new javax.swing.JTextPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnCompilar = new javax.swing.JButton();
        btnnuevo = new javax.swing.JButton();
        btnabrir = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        btnarbol = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 600));

        tabbedPane.setBackground(new java.awt.Color(255, 255, 255));
        tabbedPane.setFocusable(false);
        tabbedPane.setMinimumSize(new java.awt.Dimension(120, 50));
        tabbedPane.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabbedPaneStateChanged(evt);
            }
        });

        OutputPanel.setBackground(new java.awt.Color(255, 255, 255));

        jtaOutput.setEditable(false);
        jtaOutput.setColumns(20);
        jtaOutput.setRows(5);
        jScrollPane2.setViewportView(jtaOutput);

        javax.swing.GroupLayout OutputPanelLayout = new javax.swing.GroupLayout(OutputPanel);
        OutputPanel.setLayout(OutputPanelLayout);
        OutputPanelLayout.setHorizontalGroup(
            OutputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OutputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 970, Short.MAX_VALUE)
                .addContainerGap())
        );
        OutputPanelLayout.setVerticalGroup(
            OutputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OutputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabbedPane.addTab("Output", OutputPanel);

        TokenPanel.setBackground(new java.awt.Color(255, 255, 255));

        tblTokens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Token", "Tipo", "Posición"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTokens.setShowGrid(false);
        tblTokens.setShowVerticalLines(true);
        tblTokens.getTableHeader().setReorderingAllowed(false);
        jScrollPane5.setViewportView(tblTokens);
        if (tblTokens.getColumnModel().getColumnCount() > 0) {
            tblTokens.getColumnModel().getColumn(0).setResizable(false);
            tblTokens.getColumnModel().getColumn(1).setResizable(false);
            tblTokens.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout TokenPanelLayout = new javax.swing.GroupLayout(TokenPanel);
        TokenPanel.setLayout(TokenPanelLayout);
        TokenPanelLayout.setHorizontalGroup(
            TokenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TokenPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 970, Short.MAX_VALUE)
                .addContainerGap())
        );
        TokenPanelLayout.setVerticalGroup(
            TokenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TokenPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabbedPane.addTab("Tokens", TokenPanel);

        SimbolPanel.setBackground(new java.awt.Color(255, 255, 255));

        tblSimbol.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre", "Rol", "Tipo de dato", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSimbol.setShowGrid(false);
        tblSimbol.setShowVerticalLines(true);
        tblSimbol.getTableHeader().setReorderingAllowed(false);
        jScrollPane6.setViewportView(tblSimbol);
        if (tblSimbol.getColumnModel().getColumnCount() > 0) {
            tblSimbol.getColumnModel().getColumn(0).setResizable(false);
            tblSimbol.getColumnModel().getColumn(1).setResizable(false);
            tblSimbol.getColumnModel().getColumn(2).setResizable(false);
            tblSimbol.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout SimbolPanelLayout = new javax.swing.GroupLayout(SimbolPanel);
        SimbolPanel.setLayout(SimbolPanelLayout);
        SimbolPanelLayout.setHorizontalGroup(
            SimbolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SimbolPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 970, Short.MAX_VALUE)
                .addContainerGap())
        );
        SimbolPanelLayout.setVerticalGroup(
            SimbolPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SimbolPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabbedPane.addTab("Tabla de simbolos", SimbolPanel);

        SemanticoPanel.setBackground(new java.awt.Color(255, 255, 255));

        jtpSeman.setEditable(false);
        jScrollPane4.setViewportView(jtpSeman);

        javax.swing.GroupLayout SemanticoPanelLayout = new javax.swing.GroupLayout(SemanticoPanel);
        SemanticoPanel.setLayout(SemanticoPanelLayout);
        SemanticoPanelLayout.setHorizontalGroup(
            SemanticoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SemanticoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
        );
        SemanticoPanelLayout.setVerticalGroup(
            SemanticoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SemanticoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
        );

        tabbedPane.addTab("Semantico", SemanticoPanel);

        intermedioPanel.setBackground(new java.awt.Color(255, 255, 255));

        jtpIntermedio.setEditable(false);
        jScrollPane7.setViewportView(jtpIntermedio);

        javax.swing.GroupLayout intermedioPanelLayout = new javax.swing.GroupLayout(intermedioPanel);
        intermedioPanel.setLayout(intermedioPanelLayout);
        intermedioPanelLayout.setHorizontalGroup(
            intermedioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(intermedioPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7)
                .addContainerGap())
        );
        intermedioPanelLayout.setVerticalGroup(
            intermedioPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(intermedioPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7)
                .addContainerGap())
        );

        tabbedPane.addTab("Intermedio", intermedioPanel);

        optimizadoPanel.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane8.setBackground(new java.awt.Color(255, 255, 255));

        jtpOptimizado.setEditable(false);
        jScrollPane8.setViewportView(jtpOptimizado);

        javax.swing.GroupLayout optimizadoPanelLayout = new javax.swing.GroupLayout(optimizadoPanel);
        optimizadoPanel.setLayout(optimizadoPanelLayout);
        optimizadoPanelLayout.setHorizontalGroup(
            optimizadoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optimizadoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane8)
                .addContainerGap())
        );
        optimizadoPanelLayout.setVerticalGroup(
            optimizadoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optimizadoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane8)
                .addContainerGap())
        );

        tabbedPane.addTab("Optimizado", optimizadoPanel);

        ScrollCode.setMinimumSize(new java.awt.Dimension(250, 300));
        ScrollCode.setRowHeaderView(null);

        jtpCode.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jtpCode.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jtpCodeCaretUpdate(evt);
            }
        });
        jtpCode.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jtpCodeMouseWheelMoved(evt);
            }
        });
        ScrollCode.setViewportView(jtpCode);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ScrollCode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(ScrollCode, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("LITERACIONES");

        btnCompilar.setText("Compilar");
        btnCompilar.setMaximumSize(new java.awt.Dimension(93, 40));
        btnCompilar.setMinimumSize(new java.awt.Dimension(93, 40));
        btnCompilar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompilarActionPerformed(evt);
            }
        });

        btnnuevo.setText("Nuevo");
        btnnuevo.setMaximumSize(new java.awt.Dimension(93, 40));
        btnnuevo.setMinimumSize(new java.awt.Dimension(93, 40));
        btnnuevo.setPreferredSize(new java.awt.Dimension(93, 40));
        btnnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoActionPerformed(evt);
            }
        });

        btnabrir.setText("Abrir");
        btnabrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnabrirActionPerformed(evt);
            }
        });

        btnguardar.setText("Guardar");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        btnarbol.setText("Arbol");
        btnarbol.setEnabled(false);
        btnarbol.setMinimumSize(new java.awt.Dimension(93, 40));
        btnarbol.setPreferredSize(new java.awt.Dimension(93, 40));
        btnarbol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnarbolActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnabrir, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(btnnuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCompilar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnarbol, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnabrir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCompilar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnnuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnarbol, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        JFileChooser fileChooser = new JFileChooser();

        FileNameExtensionFilter filter = new FileNameExtensionFilter(
                "Archivos LIT (*.lit)", "lit");
        fileChooser.setFileFilter(filter);
        fileChooser.setSelectedFile(new File("Literacion.lit"));

        int opcion = fileChooser.showSaveDialog(this);
        if (opcion == JFileChooser.APPROVE_OPTION) {
            File archivo = fileChooser.getSelectedFile();

            String filePath = archivo.getAbsolutePath();

            if (!filePath.toLowerCase().endsWith(".lit")) {
                archivo = new File(filePath + ".lit");
            }

            try (FileWriter fw = new FileWriter(archivo)) {
                fw.write(jtpCode.getText());
                JOptionPane.showMessageDialog(this, "Archivo guardado correctamente.");
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "Error al guardar: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btnnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoActionPerformed
// 1. Definición de la constante para la extensión
        final String EXTENSION = ".lit";

        // Comprueba si hay texto en el área antes de preguntar
        if (!jtpCode.getText().isEmpty()) {

            // Pregunta al usuario si desea guardar
            int opcion = JOptionPane.showConfirmDialog(
                    this,
                    "¿Deseas guardar el archivo actual antes de crear uno nuevo?",
                    "Confirmar",
                    JOptionPane.YES_NO_CANCEL_OPTION
            );

            // Si el usuario elige SÍ (Guardar)
            if (opcion == JOptionPane.YES_OPTION) {

                JFileChooser fileChooser = new JFileChooser();

                FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos LIT (*.lit)", "lit");
                fileChooser.setFileFilter(filter);
                fileChooser.setSelectedFile(new File("Literacion" + EXTENSION));

                int guardar = fileChooser.showSaveDialog(this);

                if (guardar == JFileChooser.APPROVE_OPTION) {

                    File archivo = fileChooser.getSelectedFile();
                    String filePath = archivo.getAbsolutePath();

                    if (!filePath.toLowerCase().endsWith(EXTENSION)) {
                        archivo = new File(filePath + EXTENSION);
                    }

                    try (FileWriter fw = new FileWriter(archivo)) {
                        fw.write(jtpCode.getText());
                        JOptionPane.showMessageDialog(this, "Archivo guardado correctamente.");
                        jtpCode.setText("");
                    } catch (IOException ex) {
                        JOptionPane.showMessageDialog(this, "Error al guardar: " + ex.getMessage());
                    }

                }
            } else if (opcion == JOptionPane.NO_OPTION) {
                jtpCode.setText("");
            } else if (opcion == JOptionPane.CANCEL_OPTION) {
            }

        } else {
            jtpCode.setText("");
        }
    }//GEN-LAST:event_btnnuevoActionPerformed

    private void btnCompilarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompilarActionPerformed
        // Limpiar paneles de errores
        jtaOutput.setText("");
        jtpSeman.setText("");
        
        //REINICIO CODIGO INTERMEDIO ALMACENADO
        CodeGenerator.getInstance().reset();

        // ------------ ANALISIS LEXICO -----------------------------
        //Recuperamos el codigo escrito por el usuario
        String code = jtpCode.getText();

        //flujo de caracteres
        CharStream cs = CharStreams.fromString(code);

        //tokenizar el texto, le enviamos el textfield para que registre los errores
        lexer = new CustomLexer(cs, jtaOutput);

        //Buffer de tokens
        tokens = new CommonTokenStream(lexer);

        // ---------------- ANALISIS SINTACTICO -------------------------
        parser = new CustomParser(tokens, jtaOutput);

        // Se genera el arbol comenzando desde programa que es nuestro nodo inicial
        arbol = parser.programa();
        btnarbol.setEnabled(true);

        // REVISAR ERRORES LEXICOS
        List<String> LexLisErr = lexer.listaErrores;
        if (!LexLisErr.isEmpty()) {
            StringBuilder sb = new StringBuilder();
            sb.append("Se encontraron los siguientes errores lexicos:\n\n");
            for (String error : LexLisErr) {
                sb.append(error).append("\n");
            }
            jtaOutput.append(sb.toString());
        }

        //REVISAR ERRORES SEMANTICOS
        List<String> ErrorSem = parser.listaErrores;
        if (!ErrorSem.isEmpty()) {
            StringBuilder sb = new StringBuilder();
            sb.append("Se encontraron los siguientes errores semánticos:\n\n");
            for (String error : ErrorSem) {
                sb.append(error).append("\n");
            }
            jtpSeman.setText(sb.toString());
            jtaOutput.append("\n\nCompilación fallida debido a errores semánticos.");
        }

        boolean ErrorLex = lexer.listaErrores.isEmpty();

        boolean ErrorPar = parser.ErrorSintax();

        if (ErrorLex && ErrorPar && ErrorSem.isEmpty()) {
            jtaOutput.append("\n --- COMPILADO CORRECTAMENTE SIN ERRORES ---");
            jtpSeman.setText("No se encontraron errores semánticos");
        } else {
            jtaOutput.append("\n --- COMPILACION FALLIDA. -----------");
        }

        tabbedPane.setSelectedIndex(0);

        // --- FASE DE GENERACIÓN Y OPTIMIZACIÓN DE CÓDIGO 3DC ---
        // 1. Obtener la instancia del generador de código
        CodeGenerator cg = CodeGenerator.getInstance();

        // 2. Obtener el código 3DC original (tal como lo generó el parser)
        List<Instruction3DC> codigoOriginal = cg.getThreeAddressCode();

        // 🖥️ ⬇️ AQUÍ SE IMPRIME LA PRIMERA LISTA ⬇️
        System.out.println("--- CÓDIGO 3DC ORIGINAL (" + codigoOriginal.size() + " instrucciones) ---");
        StringBuilder textoIntermedio = new StringBuilder();
        textoIntermedio.append("--- CÓDIGO 3DC ORIGINAL (").append(codigoOriginal.size()).append(" instrucciones) ---\n");
        int line = 1;
        for (Instruction3DC instr : codigoOriginal) {
            System.out.println(instr);
            textoIntermedio.append(line++).append(".\t").append(instr).append("\n");
        }
        jtpIntermedio.setText(textoIntermedio.toString());
        System.out.println("---------------------------------------");

        // 3. ¡AQUÍ ES DONDE SE EJECUTA LA OPTIMIZACIÓN!
        try {
            optimizar miOptimizador = new optimizar();
            List<Instruction3DC> codigoOptimizado = miOptimizador.optimizar(codigoOriginal);

            // Imprimimos la lista optimizado
            System.out.println("--- CÓDIGO 3DC OPTIMIZADO (" + codigoOptimizado.size() + " instrucciones) ---");
            StringBuilder textoOptimizado = new StringBuilder();
            textoOptimizado.append("--- CÓDIGO 3DC OPTIMIZADO (").append(codigoOptimizado.size()).append(" instrucciones) ---\n");
            int linea = 1;
            for (Instruction3DC instr : codigoOptimizado) {
                System.out.println(instr);
                textoOptimizado.append(linea++).append(".\t").append(instr).append("\n");
            }
            jtpOptimizado.setText(textoOptimizado.toString());
            System.out.println("------------------------------------------");

        } catch (Exception e) {
            System.err.println("Error grave durante la fase de optimización: " + e.getMessage());
            e.printStackTrace();
        }


    }//GEN-LAST:event_btnCompilarActionPerformed

    private void mostrarTablaSimbolos() {

        Map<String, Simbolo> datos = parser.tablaSimbolos;

        if (this.tblSimbol == null) {
            return;
        }

// Nombres de las columnas
        String[] columnas = {"Nombre", "Valor", "Tipo"};

// Modelo de la tabla
        DefaultTableModel modelo = new DefaultTableModel(columnas, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                // Retornar false hace que ninguna celda sea editable
                return false;
            }
        };

// Recorremos el mapa y agregamos cada símbolo
        for (Map.Entry<String, Simbolo> entry : datos.entrySet()) {
            String nombre = entry.getKey();
            Object valor;
            String tipo;
            try {
                valor = entry.getValue().getValor();
                tipo = entry.getValue().getTipo();
            } catch (NullPointerException e) {
                valor = "NULO";
                tipo = "NULO";
            }

            modelo.addRow(new Object[]{nombre, valor, tipo});
        }

// Asignar el modelo a la JTable
        tblSimbol.setModel(modelo);
    }

    private void btnarbolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnarbolActionPerformed
// ... dentro de tu método donde creas la ventana del árbol ...

// 1. Crear el visor del árbol
        JFrame frame = new JFrame("Árbol de derivación");
        TreeViewer viewer = new TreeViewer(Arrays.asList(parser.getRuleNames()), arbol);
        viewer.setScale(1.5);
        viewer.setFont(new Font("Arial", Font.PLAIN, 12));

// 2. Calcular el tamaño óptimo de la ventana (Lógica Mejorada)
        Dimension treeSize = viewer.getPreferredSize();
        int treeWidth = (int) treeSize.getWidth() + 100;
        int treeHeight = (int) treeSize.getHeight() + 100;

        java.awt.GraphicsDevice gd = java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();
        int screenWidth = gd.getDisplayMode().getWidth();
        int screenHeight = gd.getDisplayMode().getHeight();

        int maxFrameWidth = (int) (screenWidth * 0.85);
        int maxFrameHeight = (int) (screenHeight * 0.85);

        int frameWidth = Math.min(treeWidth, maxFrameWidth);
        int frameHeight = Math.min(treeHeight, maxFrameHeight);

// 3. Configurar el JScrollPane
        JScrollPane scrollPane = new JScrollPane(viewer);
        scrollPane.getVerticalScrollBar().setUnitIncrement(16);
        scrollPane.getHorizontalScrollBar().setUnitIncrement(16);

// 4. AÑADIR LA FUNCIONALIDAD DE PANEO
// Creamos una instancia de nuestro listener y se la añadimos al visor del árbol
        PanListener panListener = new PanListener(viewer);
        viewer.addMouseListener(panListener);
        viewer.addMouseMotionListener(panListener);

// 5. Configurar y mostrar el JFrame
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.add(scrollPane);
        frame.setSize(frameWidth, frameHeight);
        frame.setLocationRelativeTo(this); // 'this' debe ser la ventana principal
        frame.setVisible(true);
    }//GEN-LAST:event_btnarbolActionPerformed

    private void tabbedPaneStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabbedPaneStateChanged
        // INDICES
        // 0: "Output"
        // 1: "Tokens"
        // 2: "Tabla de simbolos"
        // 3: "Semantico"
        // El índice empieza en 0.
        int Indice = tabbedPane.getSelectedIndex();

        // Comprobamos que ya se halla compilado el codigo
        if (tokens == null && Indice > 0) {
            jtaOutput.setText("Error: Debes compilar el código primero para ver detalles.");
            tabbedPane.setSelectedIndex(0);
            return; // Salimos del método
        }

        // Usamos un switch para decidir qué hacer según la pestaña seleccionada.
        switch (Indice) {
            //TOKENS
            case 1 -> {
                //System.out.println("Pestaña 'tokens' seleccionada. Mostrando tokens...");
                //   Obtenemos el "vocabulario" del lexer. Esto nos permite convertir
                //    el tipo numérico de un token (ej: 5) a su nombre en la gramática (ej: IDENTIFICADOR).
                Vocabulary vocabulary = lexer.getVocabulary();

                //Cabecera para el modelo de la tabla
                String[] TokenColumnTbl = {"Token", "Tipo", "Posición"};
                DefaultTableModel TokenModel = new DefaultTableModel(TokenColumnTbl, 0) {
                    @Override
                    public boolean isCellEditable(int row, int column) {
                        // Retornar false hace que ninguna celda sea editable
                        return false;
                    }
                };
                // 3. Recorremos cada token en la lista de tokens.
                for (Token token : tokens.getTokens()) {

                    // Obtenemos el texto del token (lo que el usuario escribió)
                    // Reemplazamos caracteres especiales para que se vean bien en una sola línea
                    String Text = token.getText()
                            .replace("\n", "\\n")
                            .replace("\r", "\\r")
                            .replace("\t", "\\t");

                    // Obtenemos el nombre simbólico del tipo de token
                    String Tipo = vocabulary.getSymbolicName(token.getType());

                    //Obtenemos la linea y columna del token
                    String Position = String.format(
                            "Línea: %d, Columna: %d\n",
                            token.getLine(),
                            token.getCharPositionInLine()
                    );

                    //Creamos un array tipo object para guardar los datos
                    Object[] filas = {Text, Tipo, Position};

                    // Finalmente los agregamos al TokenModel
                    TokenModel.addRow(filas);
                }

                // Y le definimos el modelo a la tabla que esta en la interfaz
                tblTokens.setModel(TokenModel);
            }

            //TABLA DE SIMBOLOS
            case 2 -> {
                //System.out.println("Pestaña 'tabla de simbolos' seleccionada.");
                mostrarTablaSimbolos();
            }

            //SEMANTICO
            case 3 -> {
                //System.out.println("Pestaña 'Semantica' seleccionada.");
            }
            //INTERMEDIO
            case 4 -> {

            }
            //OPTIMIZADO
            case 5 -> {

            }
            default -> {
            }
        }
    }//GEN-LAST:event_tabbedPaneStateChanged

    private void btnabrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnabrirActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
                "Archivos LIT (*.lit)", "lit");

        fileChooser.setFileFilter(filter);
        int opcion = fileChooser.showOpenDialog(this);
        if (opcion == JFileChooser.APPROVE_OPTION) {
            File archivo = fileChooser.getSelectedFile();
            try (BufferedReader br = new BufferedReader(new FileReader(archivo))) {
                StringBuilder texto = new StringBuilder();
                String linea;
                while ((linea = br.readLine()) != null) {
                    texto.append(linea).append("\n");
                }
                jtpCode.setText(texto.toString());
                jPanel1.revalidate();
                jPanel1.repaint();
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "Error al abrir: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_btnabrirActionPerformed

    private void jtpCodeCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jtpCodeCaretUpdate
        jPanel1.revalidate();
        jPanel1.repaint();
    }//GEN-LAST:event_jtpCodeCaretUpdate

    private int tam = 12; // Tamaño de fuente actual
    private final int MIN_FONT_SIZE = 12;
    private final int MAX_FONT_SIZE = 40;
    private void jtpCodeMouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jtpCodeMouseWheelMoved
        // 1. Verificar si la tecla CTRL está presionada EN ESTE MOMENTO
        if (evt.isControlDown()) {

            // 2. Obtener la dirección de la rueda del ratón
            int rotation = evt.getWheelRotation();

            if (rotation < 0) {
                // Rueda hacia arriba -> Aumentar tamaño de fuente
                if (tam < MAX_FONT_SIZE) {
                    tam++;
                }
            } else {
                // Rueda hacia abajo -> Disminuir tamaño de fuente
                if (tam > MIN_FONT_SIZE) {
                    tam--;
                }
            }

            // 3. Aplicar la nueva fuente al JTextPane
            jtpCode.setFont(new Font("Segoe UI", Font.PLAIN, tam));
            coloreador.cambiarTamaño(tam);

            numerolinea = new NumeroLinea(jtpCode);

            ScrollCode.setRowHeaderView(numerolinea);

            evt.consume();
        } else {

            // CASO 2: CTRL NO está presionado -> Hacemos SCROLL
            // Como hemos interceptado el evento, debemos reenviarlo manualmente
            // al JScrollPane para que pueda procesarlo y realizar el scroll.
            if (ScrollCode != null && ScrollCode.getVerticalScrollBar().isVisible()) {

                // Obtenemos todos los listeners de la rueda del ratón que tiene el JScrollPane
                for (java.awt.event.MouseWheelListener listener : ScrollCode.getMouseWheelListeners()) {
                    // Y le decimos a cada uno que procese el evento
                    listener.mouseWheelMoved(evt);
                }
            }
        }
    }//GEN-LAST:event_jtpCodeMouseWheelMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        FlatLightLaf.setup();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new IDE().setVisible(true));
    }

    public void clearAllComp() {
        jtaOutput.setText("");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel OutputPanel;
    public javax.swing.JScrollPane ScrollCode;
    private javax.swing.JPanel SemanticoPanel;
    private javax.swing.JPanel SimbolPanel;
    private javax.swing.JPanel TokenPanel;
    private javax.swing.JButton btnCompilar;
    private javax.swing.JButton btnabrir;
    private javax.swing.JButton btnarbol;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnnuevo;
    private javax.swing.JPanel intermedioPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTextArea jtaOutput;
    public javax.swing.JTextPane jtpCode;
    private javax.swing.JTextPane jtpIntermedio;
    private javax.swing.JTextPane jtpOptimizado;
    private javax.swing.JTextPane jtpSeman;
    private javax.swing.JPanel optimizadoPanel;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JTable tblSimbol;
    private javax.swing.JTable tblTokens;
    // End of variables declaration//GEN-END:variables
}
